spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          apple:
            client-id:
            client-name:
            authorization-grant-type:
            client-authentication-method:
            redirect-uri:
            scope:
              - gender
              - age
              - birthday

          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:${server.port}/member/sign-in/google
            scope:
              - gender
              - age
              - birthday

          naver:
            client-name: naver
            authorization-grant-type: authorization_code
            client-id:
            client-secret:
            redirect-uri: http://localhost:${server.port}/member/sign-in/naver
            scope:

          kakao:
            client-name: kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_REST_API}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:${server.port}/member/sign-in/kakao
            scope:
              - gender
              - age_range
              - birthday