spring:
  applicaion:
    name: unieat_local
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          #apple:
          #client-id:
          #client-name:
          #authorization-grant-type:
          #client-authentication-method:
          #redirect-uri:
          #scope:
          #- gender
          #- age
          #- birthday

          #google:
          #client-id:
          #client-secret:
          #redirect-uri:
          #scope:
          #- gender
          #- age
          #- birthday

          naver:
            client-name: naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/naver
            scope:
              - gender
              - age
              - birthday

          kakao:
            client-name: kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            #client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/kakao
            scope:
              - gender
              - age_range
              - birthday

server:
  port: 8088

foorun:
  unieat:
    local:
      tunnel:
        ssh:
          host: ${UNIEAT_AWS_EC2_HOST}
          username: ${UNIEAT_AWS_EC2_USERNAME}
          password: ${UNIEAT_AWS_EC2_PASSWORD}
          port: ${UNIEAT_AWS_EC2_PORT}
          prvkey: ${UNIEAT_AWS_EC2_PRV_KEY_PATH}
          lport: 0
          endpoint: ${UNIEAT_DBS_ENDPOINT}
          rport: ${UNIEAT_DBS_PORT}
logging:
  level:
    foorun:
      unieat:
        api: DEBUG