spring:
  profiles:
    include:
    - database
    - aws
    - auth

  pid:
    file: .unieat-api.pid

  application:
    admin:
      enabled: false
    name: unieat

  mvc:
    date-format: yyyy-MM-dd

server:
  shutdown: graceful